### ISSUE TITLE
Action fails with message "[error] No files matching the pattern were found"

### ISSUE THREAD

**Issue by michaelkolber** [actionsx/prettier#22]
For example: https://github.com/ClassChats/ClassChats/pull/10/checks?check_run_id=1042505214

When I run the command locally it works fine, and the files definitely exist.

**Comment by phuctm97** [comment]
It looks like you didn't check out your repository. You have to run `actions/checkout` first:

```yml
# This workflow will check that PRs use the correct style.

name: Style Check
on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check "src/**/*.ts"
```
