### ISSUE TITLE
prettier ignoring prettierrc

### ISSUE THREAD

**Issue by caevv** [actionsx/prettier#55]
No error running local, but running on Actions it will return an error:

.prettierrc.json:
```json
{
  "printWidth": 120
}
```

Action
```yml
jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettier Check
        uses: actionsx/prettier@v2
        with:
          args: --check "**/*.{js,jsx,ts,tsx}"
```
